### ISSUE TITLE
TASK [hashicorp-vault : Unseal Vault] Error on Mac OS  and Windows

### ISSUE THREAD

**Issue by boriphuth** [salecharohit/devops#7]
Hi There,
I'm executing and got some error on the final step.
How to reproduce
```
vagrant up vault.devops --provision
```
The errror in picture.
![image](https://user-images.githubusercontent.com/3132377/90961349-68c18700-e4d2-11ea-97ab-585743c3dd08.png)

**Comment by salecharohit** [comment]
Fixed it in the latest [commit](https://github.com/salecharohit/devops/commit/4a0e9da1833d3490136bc049273c18662ca544c8) please verify and acknowledge.
The newer versions of Ansible need to have a "mode" setting on else they take the default permission as 600.

**Comment by boriphuth** [comment]
Cool, let me check.

**Comment by boriphuth** [comment]
I had got a new error form TASK [Read Root Token and Save in Variable]

![image](https://user-images.githubusercontent.com/3132377/91176557-a6115900-e70c-11ea-8e61-3c054bfd73c8.png)

**Comment by salecharohit** [comment]
> I had got a new error form TASK [Read Root Token and Save in Variable]
> Suspect this vault_root_token: "{{lookup('file', '{{vault_config_directory}}/rootkey')}}"
> ![image](https://user-images.githubusercontent.com/3132377/91176557-a6115900-e70c-11ea-8e61-3c054bfd73c8.png)

Can you first destroy the vault box and then spin it up again ? following commands wil do that for you

```bash
vagrant destroy vault.devops -f
vagrant up vault.devops
```

**Comment by boriphuth** [comment]
Cool, it's work.
![image](https://user-images.githubusercontent.com/3132377/91184334-b8909000-e716-11ea-82af-375c9374e6b3.png)

**Comment by salecharohit** [comment]
> Cool, it's work.
> ![image](https://user-images.githubusercontent.com/3132377/91184334-b8909000-e716-11ea-82af-375c9374e6b3.png)

Closing this issue then :-)

**Comment by salecharohit** [comment]
> Cool, it's work.
> ![image](https://user-images.githubusercontent.com/3132377/91184334-b8909000-e716-11ea-82af-375c9374e6b3.png)

Closing this issue then :-)
